@startuml TestUML
participant BluetoothBeacon
participant NewLocationBeacon
actor user
participant NarrateMyWay
participant GUI
participant LocalStorage
participant ExternalStorage


user->NarrateMyWay : Open application
activate NarrateMyWay
note over NarrateMyWay
    Begin loop to scan for
    beacons.     
end note
NarrateMyWay->GUI : Render "Scanning" screen
NarrateMyWay<--GUI
user <- NarrateMyWay : Audio: "Scanning for beacons near you"

deactivate NarrateMyWay


NarrateMyWay <- NewLocationBeacon : "NewLocation" beacon detected within 10m
activate NarrateMyWay

NarrateMyWay -> GUI : Render "New Location Discovered" screen
NarrateMyWay <-- GUI

note over NarrateMyWay
    Process new location detection (see other image)
end note

NarrateMyWay -> GUI : Render "Scanning" screen
NarrateMyWay <-- GUI

user <- NarrateMyWay : Audio: "Scanning for beacons near you"

deactivate NarrateMyWay


user<-BluetoothBeacon : Beacon detected within 10m
user<-BluetoothBeacon : Code: "nmw:1-0-1" & UUID: 98765
user->NarrateMyWay : Determine information for the given code & UUID
activate NarrateMyWay
note over NarrateMyWay : Terminate loop

group (Optional) UUID information available
NarrateMyWay->LocalStorage : Check if UUID is available in local storage
NarrateMyWay<--LocalStorage : Provide enriched information
end

NarrateMyWay->LocalStorage : Fetch encoding information
activate LocalStorage
note over LocalStorage 
    Determine meaning of code including:
    - Type of location (POI or Warning etc.)
    - Name and icon for location
    - Required audio output (in chosen language)    
end note
NarrateMyWay<--LocalStorage
deactivate LocalStorage
NarrateMyWay->GUI: Render "Main" screen using this information
NarrateMyWay<--GUI
user <- NarrateMyWay : Audio: Play required audio snippet
...Allow user to engage with app and repeat audio etc...

BluetoothBeacon->user : Beacon no longer detected
note over NarrateMyWay
    Begin loop to scan for
    beacons.     
end note
user->NarrateMyWay : (In background) Notify that beacon no longer detected
NarrateMyWay->GUI : Render "Scanning" screen
NarrateMyWay<--GUI
user <- NarrateMyWay : Audio: "Scanning for beacons near you"

deactivate NarrateMyWay

@enduml